//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application description page..
        /// </summary>
        public static string AboutMessage {
            get {
                return ResourceManager.GetString("AboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreements.
        /// </summary>
        public static string AgreementTileText {
            get {
                return ResourceManager.GetString("AgreementTileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your contact page..
        /// </summary>
        public static string ContactMessage {
            get {
                return ResourceManager.GetString("ContactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Order Failed.
        /// </summary>
        public static string CreateOrderError {
            get {
                return ResourceManager.GetString("CreateOrderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Order Successfully!.
        /// </summary>
        public static string CreateOrderMessage {
            get {
                return ResourceManager.GetString("CreateOrderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship To Delete Successfully..
        /// </summary>
        public static string DeleteShipmentAddressMessage {
            get {
                return ResourceManager.GetString("DeleteShipmentAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AgreementNumber cannot be empty or its max length is 12.
        /// </summary>
        public static string Error_AgreementNumberEmptyOrOverMaxLength {
            get {
                return ResourceManager.GetString("Error_AgreementNumberEmptyOrOverMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item&apos;s Billing Option cannot be empty.
        /// </summary>
        public static string Error_BillingOptionEmpty {
            get {
                return ResourceManager.GetString("Error_BillingOptionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Partner Number cannot be empty.
        /// </summary>
        public static string Error_DirectPartnerNumberEmpty {
            get {
                return ResourceManager.GetString("Error_DirectPartnerNumberEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Search input is not valid.
        /// </summary>
        public static string Error_InvalidSearchParam {
            get {
                return ResourceManager.GetString("Error_InvalidSearchParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item&apos;s OrderQuantity must be &gt; 0 and &lt; 10000000.
        /// </summary>
        public static string Error_OrderQuantityNotInRange {
            get {
                return ResourceManager.GetString("Error_OrderQuantityNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item&apos;s PartNumber cannot be empty and its max length is 16.
        /// </summary>
        public static string Error_PartNumberEmptyOrOverMaxLength {
            get {
                return ResourceManager.GetString("Error_PartNumberEmptyOrOverMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item&apos;s Program Offering cannot be empty.
        /// </summary>
        public static string Error_ProgramOfferingEmpty {
            get {
                return ResourceManager.GetString("Error_ProgramOfferingEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PurchaseOrderNumber cannot be empty or its max length is 30.
        /// </summary>
        public static string Error_PurchaseOrderNumberEmptyOrOverMaxLength {
            get {
                return ResourceManager.GetString("Error_PurchaseOrderNumberEmptyOrOverMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order Type cannot be empty.
        /// </summary>
        public static string Error_PurchaseOrderTypeEmpty {
            get {
                return ResourceManager.GetString("Error_PurchaseOrderTypeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item&apos;s Unit Quantity cannot be empty.
        /// </summary>
        public static string Error_UnitQuantityEmpty {
            get {
                return ResourceManager.GetString("Error_UnitQuantityEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item&apos;s Usage Country cannot be empty.
        /// </summary>
        public static string Error_UsageCountryEmpty {
            get {
                return ResourceManager.GetString("Error_UsageCountryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UsageDate cannot be empty.
        /// </summary>
        public static string Error_UsageDateEmpty {
            get {
                return ResourceManager.GetString("Error_UsageDateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpTileText {
            get {
                return ResourceManager.GetString("HelpTileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Users.
        /// </summary>
        public static string ManageUserTileText {
            get {
                return ResourceManager.GetString("ManageUserTileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO..
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string OrderTileText {
            get {
                return ResourceManager.GetString("OrderTileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quoting.
        /// </summary>
        public static string QuotingTileText {
            get {
                return ResourceManager.GetString("QuotingTileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting.
        /// </summary>
        public static string ReportingTileText {
            get {
                return ResourceManager.GetString("ReportingTileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Draft Order Successfully..
        /// </summary>
        public static string SaveDraftOrderMessage {
            get {
                return ResourceManager.GetString("SaveDraftOrderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship To Address Saved Successfully..
        /// </summary>
        public static string SaveShipmentAddressMessage {
            get {
                return ResourceManager.GetString("SaveShipmentAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a result against the keyword.
        /// </summary>
        public static string SearchSkuMessage {
            get {
                return ResourceManager.GetString("SearchSkuMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Licensing Partner Center.
        /// </summary>
        public static string VolumeLicensingPartnerCenter {
            get {
                return ResourceManager.GetString("VolumeLicensingPartnerCenter", resourceCulture);
            }
        }
    }
}
